import React, { useState } from 'react';
import { Link } from 'react-router-dom';
const notice='仅用于原型演示，未经专业审核';
function Frame({title,children}:{title:string;children:React.ReactNode}){return <div className="generic-page"><div className="demo-notice" role="note">{notice} · demoOnly=true · reviewStatus=DEMO_UNREVIEWED · publishable=false</div><h1>{title}</h1>{children}</div>}
export function Phase3Page({kind}:{kind:string}){switch(kind){case'consent':return <Consent/>;case'screening':return <Screening/>;case'profile':return <Profile/>;case'today':return <Today/>;case'diet':return <Diet/>;case'training-live':return <Training/>;case'training-retro':return <Retro/>;case'weekly-feedback':return <Feedback/>;case'safety':return <Safety/>;case'messages':return <Messages/>;case'data':return <Data/>;default:return <WebOps title={kind}/>}}
function Consent(){const[ok,setOk]=useState(false);return <Frame title="知情说明与授权"><p>请阅读演示说明。</p><label><input type="checkbox" checked={ok} onChange={e=>setOk(e.target.checked)}/>我已阅读并理解</label><Link className="button" aria-disabled={!ok} to={ok?'/h5/screening':'#'}>继续筛查</Link></Frame>}
function Screening(){const[s,setS]=useState('');const options:[string,string][]=[['approved','通过'],['human-review','人工复核'],['stopped','停止流程']];return <Frame title="健康风险筛查"><p>不会提供诊断。</p>{options.map(([v,l])=><button className="button" key={v} onClick={()=>setS(v)}>{l}</button>)}{s&&<div role="status" className="state-panel">{s}</div>}</Frame>}
function Profile(){return <Frame title="分阶段建档"><p>草稿可恢复，矛盾资料会阻断。</p><button className="button">保存当前步骤</button></Frame>}
function Today(){const[s,setS]=useState('pending-confirmation');const t=s==='scheduled'?['饮食记录','训练逐组记录']:s==='risk-paused'?['饮食记录']:[];return <Frame title="今日任务"><p>待确认、超时、空档不生成任务。</p>{['pending-confirmation','confirmation-timeout','plan-gap','scheduled','risk-paused'].map(x=><button className="button button--secondary" key={x} onClick={()=>setS(x)}>{x}</button>)}<div className="state-panel" role="status">{t.length?t.map(x=><p key={x}>{x}</p>):'当前没有可执行任务'}</div></Frame>}
function Diet(){const[s,setS]=useState('');const[r,setR]=useState('');return <Frame title="饮食记录"><select aria-label="执行状态" value={s} onChange={e=>setS(e.target.value)}><option value="">选择状态</option><option value="on-plan">按计划</option><option value="partial">部分偏离</option><option value="clear-deviation">明显偏离</option></select>{s&&s!=='on-plan'&&<input aria-label="偏离原因" value={r} onChange={e=>setR(e.target.value)}/>}<button className="button" disabled={!s||(s!=='on-plan'&&!r.trim())}>提交记录</button></Frame>}
function Training(){const[p,setP]=useState(false);return <Frame title="训练逐组记录"><label><input type="checkbox"/>第1组完成</label><label><input type="checkbox" onChange={e=>setP(e.target.checked)}/>出现疼痛</label>{p&&<div role="alert" className="state-panel">关联动作已暂停，进入人工处理。<Link to="/h5/safety-review">安全处理</Link></div>}</Frame>}
function Retro(){return <Frame title="训练事后补录"><p>冲突时不静默覆盖。</p><textarea aria-label="补录说明"/><button className="button">保存补录</button></Frame>}
function Feedback(){return <Frame title="周反馈"><p>提交后进入调整等待；数据不足时保持当前方案并等待人工调整。</p><textarea aria-label="周反馈"/><button className="button">提交反馈</button></Frame>}
function Safety(){return <Frame title="安全阻断与人工复核"><div role="alert" className="state-panel">影响范围：关联训练。下一步：联系运营。</div></Frame>}
function Messages(){return <Frame title="消息中心"><button className="button">标记已读</button><Link className="button" to="/h5/safety-review">打开消息</Link></Frame>}
function Data(){return <Frame title="数据导出与删除"><button className="button">提交导出或删除请求</button></Frame>}
function WebOps({title}:{title:string}){const[s,setS]=useState('待处理');return <Frame title={title}><div className="state-panel">状态：{s}</div><button className="button" onClick={()=>setS('已接单')}>接单</button><button className="button button--secondary" onClick={()=>setS('等待补充')}>请求补充</button><button className="button" disabled>真人发布（禁用）</button></Frame>}
